export const API_ROUTES = {
  projects: '/api/projects',
  project: '/api/projects/:id',
  epics: '/api/projects/:projectId/epics',
  epic: '/api/projects/:projectId/epics/:id',
  tickets: '/api/tickets',
  ticket: '/api/tickets/:id',
  ticketsByEpic: '/api/epics/:epicId/tickets',
  ticketStatus: '/api/tickets/:id/status',
  ticketArtifacts: '/api/tickets/:id/artifacts',
  sprints: '/api/projects/:projectId/sprints',
  sprint: '/api/projects/:projectId/sprints/:id',
  patternRegistry: '/api/projects/:projectId/patterns',
  pattern: '/api/projects/:projectId/patterns/:id',
  ticketPatterns: '/api/tickets/:ticketId/patterns',
  ticketPattern: '/api/tickets/:ticketId/patterns/:patternId',
  contextBundle: '/api/projects/:projectId/tickets/:ticketId/context-bundle',
  estimateTokens: '/api/projects/:projectId/tickets/:ticketId/estimate-tokens',
  agentSessions: '/api/agent-sessions',
  agentSession: '/api/agent-sessions/:id',
} as const;
