// Enums and constants
export {
  TicketCategory,
  TICKET_CATEGORIES,
  TicketStatus,
  TICKET_STATUSES,
  Criticality,
  CRITICALITIES,
  EpicStatus,
  EPIC_STATUSES,
  ArtifactType,
  AgentType,
  AgentSessionStatus,
  AGENT_SESSION_STATUSES,
  AgentPhase,
  AgentModel,
  AGENT_MODELS,
  AGENT_MODEL_LABELS,
  DEFAULT_AGENT_MODEL,
  getDefaultModelForCriticality,
  PatternType,
  PATTERN_TYPES,
  VALID_TRANSITIONS,
  VALID_SESSION_TRANSITIONS,
} from './enums.js';

// Types
export type {
  Project,
  Epic,
  Ticket,
  TicketArtifact,
  AcceptanceCriterion,
  Sprint,
  PatternEntry,
  TicketPattern,
  LinkedPattern,
  ContextBundle,
  ContextBundleTier1,
  ContextBundleTier2,
  ContextBundleTier3,
  TokenEstimate,
  AgentSession,
  WsClientMessage,
  WsServerMessage,
  WsSubscribeMessage,
  WsUnsubscribeMessage,
  WsConnectedEvent,
  WsOutputChunkEvent,
  WsToolUseEvent,
  WsToolResultEvent,
  WsStatusChangeEvent,
  WsArtifactCapturedEvent,
  WsTokenUpdateEvent,
  WsErrorEvent,
  WsSessionCompleteEvent,
} from './types/index.js';

// Schemas
export {
  createProjectSchema,
  updateProjectSchema,
  createEpicSchema,
  updateEpicSchema,
  createTicketSchema,
  updateTicketSchema,
  updateTicketStatusSchema,
  acceptanceCriterionSchema,
  createSprintSchema,
  updateSprintSchema,
  createPatternSchema,
  updatePatternSchema,
  tokenBudgetSchema,
  createAgentSessionSchema,
  deployAgentSchema,
  approveRejectPlanSchema,
} from './schemas/index.js';

export type {
  CreateProjectInput,
  UpdateProjectInput,
  CreateEpicInput,
  UpdateEpicInput,
  CreateTicketInput,
  UpdateTicketInput,
  UpdateTicketStatusInput,
  CreateSprintInput,
  UpdateSprintInput,
  CreatePatternInput,
  UpdatePatternInput,
  TokenBudgetInput,
  CreateAgentSessionInput,
  DeployAgentInput,
  ApproveRejectPlanInput,
} from './schemas/index.js';

// API
export { API_ROUTES } from './api/index.js';
